### ISSUE TITLE
不知道怎么调用类和接受类的返回值，如果有解析json的需求怎么实现

### ISSUE THREAD

**Issue by sd3970566** [liangchenhe55/Android-Lua#11]
不知道怎么调用类和接受类的返回值，如果有解析json的需求怎么实现

**Comment by ichenhe** [comment]
抱歉回复晚了。
不是很懂你的意思，解析 Json 需要自行在 java 实现，然后留个接口返回给 lua。类型是个 `table` 就行。

**Comment by sd3970566** [comment]
你能帮我定制一下LUA执行脚本的那个入口吗。我能给你发点红包，我不想lua文件被别人跟踪或者反编译解密！目前我是把lua文件RC4加密后保存在设备的SD卡上，执行之前读入文件并且RC4解密后给java使用
但是跟踪者只需在 安卓java代码的 LdoString 地方 下断即可得到我解密后传入作为参数的lua明文。大佬有空的话能给个联系方式吗


您能帮我修改一下 So库的 luadoString 实现的过程吗·，我希望在SO库里的&nbsp; luadostrig里 进行 RC4解密再执行脚本。
比如&nbsp; lua.LdoString(String 脚本文本, Boolean 是否进行so库解密后执行, String 解密RC4密码)//  当参数二 为真的时候 就从SO库内部解密执行脚本，当参数二为假的时候 就不解密直接正常执行脚本内容
















---------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chenhe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 下午3:53
收件人:&nbsp;"liangchenhe55/Android-Lua"<Android-Lua@noreply.github.com&gt;;
抄送:&nbsp;"381238114"<381238114@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liangchenhe55/Android-Lua] 不知道怎么调用类和接受类的返回值，如果有解析json的需求怎么实现 (#11)





 
抱歉回复晚了。
 不是很懂你的意思，解析 Json 需要自行在 java 实现，然后留个接口返回给 lua。类型是个 table 就行。

**Comment by ichenhe** [comment]
### 关于 json

抱歉，现在没空接定制。不过可以给你一个提示：如果只是简单的 json （json格式已知），那么直接使用 java json 库 (moshi/gson/fastjson 等) 解析出 javabean 后再[注入 Lua 表](https://github.com/liangchenhe55/Android-Lua/#%E6%B3%A8%E5%85%A5-lua-%E8%A1%A8)就行了。

如果是脏数据（json 格式未知），那么你需要使用相关库的底层API （对于 gson/fastjson 可以解析为中间层，对 moshi 需要使用流式 API），遍历出所具有的字段，然后再写入 Lua 表。这个情况比较麻烦。

如果你想在 Lua 上实现类似 java 的API （传入一个 class 然后自动返回解析后的实例），那么需要自己写一个中间层用于把 lua 和 java class 进行对应。

> 如果不想注入 Lua 表，也可以直接注入[解析后的 java 对象](https://github.com/liangchenhe55/Android-Lua/#%E6%B3%A8%E5%85%A5-java-%E5%AF%B9%E8%B1%A1)，但是不建议，因为性能比较差。


### 关于安全

所有本地代码根本不存在安全的保证，无非是 java 层解密更容易破解，jni 层解密不容易破解罢了。你的需求大概实现流程是：java 传一个文件到 JNI，JNI 读取此文件，进行解密，然后直接传给 lua 执行，最后结果返回 java. 由于我对 Android Native API 不太熟悉，所以抱歉无法帮你实现。
