### ISSUE TITLE
Call function from another lua file

### ISSUE THREAD

**Issue by MohsenAbdelkareem** [liangchenhe55/Android-Lua#12]
How to import another lua file and call function from it ?
i got this error :

1: string = '[string "require "import"..."]:1: module 'import' not found:
    	no field package.preload['import']
    	no file '/usr/local/share/lua/5.3/import.lua'
    	no file '/usr/local/share/lua/5.3/import/init.lua'
    	no file '/usr/local/lib/lua/5.3/import.lua'
    	no file '/usr/local/lib/lua/5.3/import/init.lua'
    	no file './import.lua'
    	no file './import/init.lua'
    	no file '/usr/local/lib/lua/5.3/import.so'
    	no file '/usr/local/lib/lua/5.3/loadall.so'
    	no file './import.so''
    2: string = 'attempt to call a nil value'

**Comment by ichenhe** [comment]
Just call `lua.LdoFile()` or `lua.LdoString()` to load a lua script file. After that all function in this script will be loaded.

**Comment by ichenhe** [comment]
If you want to import other file in lua, please inject a function to lua, see [here](https://github.com/liangchenhe55/Android-Lua#lua-%E8%B0%83%E7%94%A8-java-%E5%87%BD%E6%95%B0). I mean only java can load lua files, so you have to inject a java function to lua to do that.

call stack: lua → java → LdoFile()

Sorry, no English documentation is available at present.
