### ISSUE TITLE
能多线程执行么 怎么写好一点呢

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [liangchenhe55/Android-Lua#13]
能多线程执行么 怎么写好一点呢

**Comment by ichenhe** [comment]
你有两个选择:

- 直接从多线程环境中执行 lua 脚本。
- 利用 java 绑定从 lua 中启动新线程并注册回调。[看这里](https://github.com/liangchenhe55/Android-Lua#lua-%E5%9B%9E%E8%B0%83-http-%E8%AF%B7%E6%B1%82)
