### ISSUE TITLE
怎么导入lua-resty-http

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [liangchenhe55/Android-Lua#14]
怎么导入lua-resty-http

**Comment by ichenhe** [comment]
不太了解这个库。
一般来讲，lua 是没有网络访问功能的，所以实现此功能的库其实都是进行了函数注入。那么注入的函数需要一个运行环境。举个例子：你自己把 okhttp 注入了 lua 那么就可以访问网络，**但是这一脚本需要 okhttp 运行环境**。

我的意思就是，能执行 lua 脚本 ≠ 能使用 lua 库。首先你得先确认相关库所依赖的环境在目标设备上是ok的，然后，加载库和执行脚本是一样的，直接 load 就行了。
