### ISSUE TITLE
lua.openLibs();怎么open resty.http呢

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [liangchenhe55/Android-Lua#15]
lua.openLibs();怎么open resty.http呢

**Comment by ichenhe** [comment]
`openLibs` 用于载入 lua 标准库。不是加载第三方库用的。

Lua 严格来讲根本没有库的概念，也没有统一的导入方法。Lua 库与普通的脚本没有区别，直接执行就行了。执行后这个脚本的定义的函数就相当于被导入了。

参见 [加载 lua 脚本](https://github.com/liangchenhe55/Android-Lua#%E5%8A%A0%E8%BD%BD-lua-%E8%84%9A%E6%9C%AC)

---

请您自行学习更多关于 Lua 本身以及 `resty.http` Lib 的相关知识。本项目仅仅是实现一个 Lua Core 的 Android 运行环境。因为 Lua 语言的特殊性，一个 Lib 往往对环境有较大的依赖，请不要把 Lua 语言的跨平台等价于 Lua 库的跨平台。

**Comment by ichenhe** [comment]
在 Android 上强行使用其他平台的 Lua 网络库是行不通的。

你应当自己绑定适用于 Android 的网络模块。[AndroLua+](https://github.com/nirenr/AndroLua_pro) 项目实现了 Lua 在 Android 的完整绑定，甚至可以直接用 Lua 开发 Android App，当然也包括 http 绑定。

但是这个项目文档比较乱，似乎也不维护了，仅供参考。

**Comment by MarsDiplomatToEarth** [comment]
好的 谢谢解答

**Comment by MarsDiplomatToEarth** [comment]
lua怎么绑定android的网络模块呢 androlua好像运行不了

**Comment by ichenhe** [comment]
关于回调绑定请参见 [Lua 回调 （HTTP 请求）](https://github.com/liangchenhe55/Android-Lua/#lua-%E5%9B%9E%E8%B0%83-http-%E8%AF%B7%E6%B1%82)

关于 HTTP 在 java 端的具体实现请考虑使用：[OkHttp](https://github.com/square/okhttp)，或者他的简化封装 [okhttputils](https://github.com/hongyangAndroid/okhttputils)，或者高级封装 [Retrofit](https://github.com/square/retrofit)。

你的问题已经超出本项目范畴，请自行学习如何在 Android 端访问 HTTP，学会了之后把相关的 API [注入 Lua](https://github.com/liangchenhe55/Android-Lua/#lua-%E8%B0%83%E7%94%A8-java-%E5%87%BD%E6%95%B0) 即可。
