### ISSUE TITLE
能不能有什么办法加密LUA

### ISSUE THREAD

**Issue by sd3970566** [liangchenhe55/Android-Lua#16]
能不能有什么办法加密LUA,跟踪者只要在dostring下断就能看到lua明文·

**Comment by ichenhe** [comment]
没有，事实上这是所有脚本语言的通病。

你可以自行对脚本进行加密，例如 AES，但是密钥很容易泄露。其本质原因是任何本地加密解密行为都无法保证绝对的安全。

或者考虑使用 [Lua-JIT](https://github.com/liangchenhe55/Android-LuaJIT) 他可以编译成跨平台的字节码。虽然也有反编译的可能性，但总好过明文。

**Comment by sd3970566** [comment]
Lua-JIT 我好像试过不行，我用 Lua-JIT 一键加密工具编译出来放我们的lua上执行不了·。能不能推荐一个加密工具？

**Comment by ichenhe** [comment]
为什么非要用一键加密？自己用luajit官方版编译不行吗？

我也不知道有什么加密工具。

**Comment by ichenhe** [comment]
关于 Windows 下编译 Lua-JIT 字节码参考[这篇博客](https://www.jianshu.com/p/fc4bee82c3ef)。
