### ISSUE TITLE
如果我要ECLIPSE使用这个的话，怎么引用！我需要在AS里打包成So库或者JAR再给ECLIPSE使用吗

### ISSUE THREAD

**Issue by sd3970566** [liangchenhe55/Android-Lua#17]
如果我要ECLIPSE使用这个的话，怎么引用！我需要在AS里打包成So库或者JAR再给ECLIPSE使用吗
能不能教我一下！ 因为咱的LUA不支持中文变量和中文函数名。我在网上查了一下。修改了CPP里的一些东西。现在能支持中文了。但是又想再ECLIPSE的IDE里使用。不知道怎么转过去！

**Comment by ichenhe** [comment]
我更新后已经可以支持中文了。

Eclipse 我也不会用。大概就是把 so 库复制到对应的文件夹下，然后把 java 编译的 jar 文件也复制过去并作为依赖。

如果你想自己编译，那么需要先配置 NDK 环境。

另外麻烦请不要再一直开与本项目无明显关联的 Issue，这里不作为开发教学的平台，谢谢。

最后，查不到是正常的，Eclipse 很早很早就过时了，与大部分现代化 Android 组件均不兼容或难以兼容。如果你依然在使用这个古老的 IDE 那么应该考虑迁移，如果你的团队在使用这个，那么应该考虑说服一下 Leader 或 886~
