### ISSUE TITLE
怎么直接执行import 安卓包来导入安卓包呢 

### ISSUE THREAD

**Issue by tghjnjvg** [liangchenhe55/Android-Lua#18]
直接执行import 安卓包来导入安卓包呢

**Comment by ichenhe** [comment]
不懂你想问什么。

如果是想在 lua 中执行 import 来导入其他 lua 文件，参阅[这个回复](https://github.com/liangchenhe55/Android-Lua/issues/12#issuecomment-602168431)

**Comment by ichenhe** [comment]
如果你想在 lua 中直接引用 java 包这恐怕是不行的。

所有 java 对象必须显式地注入后才能使用，参阅[注入 java 对象](https://github.com/liangchenhe55/Android-Lua#%E6%B3%A8%E5%85%A5-java-%E5%AF%B9%E8%B1%A1)

**Comment by tghjnjvg** [comment]
https://github.com/L-JINBIN/AndroidLua/实现类似这种效果的

**Comment by tghjnjvg** [comment]
https://github.com/L-JINBIN/AndroidLua/
实现类似这种效果的

**Comment by tghjnjvg** [comment]
使用 "包名+类名" 访问 Java 类
import "bin.androidlua.TestObject"
test = TestObject()
-- 也可以写成
test = bin.androidlua.TestObject()
但不支持内部类，例如访问 TestObject.TwoMethod 时，得这么写

import "bin.androidlua.*"
TwoMethod = TestObject_TwoMethod -- TestObject$TwoMethod

它这个我用不了 报错了 写的太复杂也不知道从哪里入手

**Comment by tghjnjvg** [comment]
这是它项目import lua的代码 我怎么在你这个项目使用呢大佬
local packages = {}
local append = table.insert
local new = luajava.new

-- SciTE requires this, if you want to see stdout immediately...

io.stdout:setvbuf 'no'
io.stderr:setvbuf 'no'

local function new_tostring (o)
    return o:toString()
end

function tryCatch(funs)
    local e
    if not xpcall(funs[1], function(err) e = err end) then
        if (type(e) == "string") then
            -- 跳过当前这个function的traceback
            funs[2](e .. '\n' .. debug.tracebackSkip(1), false)
        else
            funs[2](e, true)
        end
        return false
    end
    return true
end

function __java_class_call (t, ...)
    local stat, obj = pcall(new, t, ...)
    if not stat then
        error("cannot new instance of " .. t.toString())
    end
    getmetatable(obj).__tostring = new_tostring
    return obj
end

local function import_class (classname, packagename)
    local res, class = pcall(luajava.bindClass, packagename)
    if res then
        _G[classname] = class
        local mt = getmetatable(class)
        mt.__call = __java_class_call
        return class
    end
end

local function massage_classname (classname)
    if classname:find('_') then
        classname = classname:gsub('_', '$')
    end
    return classname
end

local globalMT = {
    __index = function(table, classname)
        classname = massage_classname(classname)
        for i, p in ipairs(packages) do
            local class = import_class(classname, p .. classname)
            if class then
                return class
            end
        end
        error("import cannot find " .. classname)
    end
}
setmetatable(_G, globalMT)

function import (package)
    local i = package:find('%.%*$')
    if i then
        -- a wildcard; put into the package list, including the final '.'
        append(packages, package:sub(1, i))
    else
        local classname = package:match('([%w_]+)$')
        if not import_class(classname, package) then
            error("cannot find " .. package)
        end
    end
end

append(packages, '')

import 'java.lang.*'
import 'java.util.*'

**Comment by ichenhe** [comment]
请先阅读这个 [wiki](https://github.com/liangchenhe55/Android-Lua/wiki/Third-party-Lua-lib_zh)

另外，你所提到的项目说的很清楚：

> Lua 的 Android 加强版实现

而本项目仅仅是 Lua C API 的 JNI 标准实现，所以 API 都是按照 Lua 的 C API 原样（AS IS）提供，没有过多的扩展功能，所以不能实现。
