### ISSUE TITLE
如果lua脚本有错怎么获取呢？

### ISSUE THREAD

**Issue by Jinnrry** [liangchenhe55/Android-Lua#2]
非常感谢作者这个项目，我有个小问题，按照demo改的，
`
lua.LdoString(readAssetsTxt(this, "main.lua"));
`
如果这个脚本报错了，java代码中怎么能知道呢？或者有其他办法抛出也行

**Comment by ichenhe** [comment]
`lua.LdoString` 会返回一个 `int`，`0` 表示没有错误，否则有错。如果有错误那么错误信息会直接入栈，通过 `luaState.toString(-1)` 可以拿到。

不好意思最近比较忙现在才想起来回复。

**Comment by Jinnrry** [comment]
十分感谢
