### ISSUE TITLE
怎么样查看lua代码的报错信息，那有没有办法调试lua代码呀类似于断点

### ISSUE THREAD

**Issue by TangJhan** [liangchenhe55/Android-Lua#22]

**Comment by ichenhe** [comment]
请仔细阅读 [加载 lua 脚本](https://github.com/liangchenhe55/Android-Lua/#%E5%8A%A0%E8%BD%BD-lua-%E8%84%9A%E6%9C%AC)。

> 使用 lua.LdoString() 可以轻松执行一段 Lua 代码。通过其返回值可以判断执行是否成功。0 表示成功否则表示不成功。**若不成功则错误信息会直接入栈，我们可以通过 lua.toString(-1) 获取到。**

没有断点调试。

**Comment by TangJhan** [comment]
谢谢回答，已经解决了，使用MobDebug进行断点调试就OK了
