### ISSUE TITLE
package.path在android中默认的路径是哪？

### ISSUE THREAD

**Issue by TangJhan** [liangchenhe55/Android-Lua#23]

**Comment by ichenhe** [comment]
还真不清楚。不妨输出一下看看。

建议不要使用原生的 require 以免因为路径或权限问题找不到文件。你应该使用 java 向 lua 注入一个函数，绑定到 `lua.LdoString()` 或 `lua.LdoFile()` 来完全自己控制加载过程。

**Comment by TangJhan** [comment]
好的，已经解决了路径和加载三方lua的问题
