### ISSUE TITLE
如何访问java类的属性呢？

### ISSUE THREAD

**Issue by zhouweiwansui** [liangchenhe55/Android-Lua#34]
public class TrainRecord {
    public String student_id;
}
这个类作为参数传入lua函数里面
这样的属性如何访问？再lua里面用TrainRecord.student_id访问不行

**Comment by ichenhe** [comment]
注意 lua 的基本语法。lua 类成员的访问不是直接用 `.`，而是冒号 `:`，本质上是一个语法糖。

另外 demo 中也演示了。「注入 java 对象」就是。
