### ISSUE TITLE
请问如何调用luac编译过的lua文件呢？

### ISSUE THREAD

**Issue by woolen-sheep** [liangchenhe55/Android-Lua#37]
编写的lua脚本中的函数可以正常调用
lua脚本由luac编译之后可以正常加载，但是调用`lua.pcall`时返回`attempt to call a nil value`

**Comment by ichenhe** [comment]
lua 不是跨架构的。在电脑上(x64)编译出来的 lua 字节码不可以在手机上(arm)执行。

lua 字节码的交叉编译我曾经尝试过，无果。此需求建议使用 [Lua JIT](https://github.com/ichenhe/Android-LuaJIT) 实现，但是这东西停更了。

**Comment by woolen-sheep** [comment]
通过在arm下编译luac解决了，多谢指点。
