### ISSUE TITLE
Nokia C20 Plus load lua  fail

### ISSUE THREAD

**Issue by 123yangu** [liangchenhe55/Android-Lua#38]
诺基亚Nokia C20 Plus手机机型加载lua,调用lua方法失败，报错attempt to call a nil value

**Comment by 123yangu** [comment]
使用不加密lua脚本LdoString(data)可以正常使用，但是使用加密脚本则报错attempt to call a nil value

**Comment by ichenhe** [comment]
加密？你是说编译吗。lua 字节码不是跨架构的。x86 编译的不能在 arm 手机读取。如有这种需求，要不用相同架构编译，要么用 [Lua JIT](https://github.com/ichenhe/Android-LuaJIT)。

**Comment by 123yangu** [comment]
> 加密？你是说编译的。lua 不是码跨架构的。x86 编译的在arm 手机不能用吗。这种情况需要不用相同架构编译，或者使用[Lua JIT](https://github.com/ichenhe/Android-LuaJIT)。
我们对lua脚本进行了加密

**Comment by 123yangu** [comment]
目前使用方式如果使用lua文件明文的形式加载LdoString，功能都是正常的，但是如果使用加密过的lua文件则，使用回报错，在Nokia C20 Plus手机上

**Comment by ichenhe** [comment]
不懂你说的加密是什么意思。加密了当然不能执行了。要不自己改 lua 虚拟机代码重新编译。lua 就是一个解释器，你把脚本改了，print() 变成了 abc() 解释器咋执行

**Comment by 123yangu** [comment]
> 不懂你说的加密是什么意思。加密了当然不能执行了。要不自己改 lua 虚拟机代码重新编译。lua 就是一个解释器，你把脚本改了，print() 变成了 abc() 解释器咋执行

就是用lua c默认的加密方式进行lua脚本加密
加密后的文件截图
![image](https://user-images.githubusercontent.com/6700363/179434131-7d2d7153-9349-4292-9091-ef4bfc1f55c1.png)

不加密截图
![image](https://user-images.githubusercontent.com/6700363/179434175-b1b3b47a-eec3-4854-88b3-b40bc337803a.png)

**Comment by ichenhe** [comment]
> 就是用lua c默认的加密方式进行lua脚本加密

依然不懂这是啥。lua 原生没有所谓的加密。只有编译。编译后的字节码不是跨架构的，你在 x86 电脑编译的 lua 不能在 arm 设备执行。具体二楼已经说过了。

如果你坚持加密不是编译，要不把加密命令放上来看看。

PS：从截图看，你这就是编译，不是所谓的“加密”。不是说从明文变成了二进制就叫加密的。建议仔细学习下 lua 字节码相关知识。

PS2：`LdoString` 只能执行字符串源码。编译后的字节码（假设相同 cpu 架构）需要用 `LdoFile` 载入。

**Comment by 123yangu** [comment]
> > 就是用lua c默认的加密方式进行lua脚本加密
> 
> 依然不懂这是啥。lua 原生没有所谓的加密。只有编译。编译后的字节码不是跨架构的，你在 x86 电脑编译的 lua 不能在 arm 设备执行。具体二楼已经说过了。
> 
> 如果你坚持加密不是编译，要不把加密命令放上来看看。
> 
> PS：从截图看，你这就是编译，不是所谓的“加密”。不是说从明文变成了二进制就叫加密的。建议仔细学习下 lua 字节码相关知识。
> 
> PS2：`LdoString` 只能执行字符串源码。编译后的字节码（假设相同 cpu 架构）需要用 `LdoFile` 载入。

我这边的脚本使用Luac的方式进行加密，在cmd中，输入luac -o out.lua xxx.lua(源文件地址)，加密之后，我这边是用LdoFile的方式导入脚本

**Comment by ichenhe** [comment]
> 我这边的脚本使用Luac的方式进行加密

@123yangu  再再说一遍，luac 叫**编译**，不叫~~加密~~。请不要混用这两个词汇（尽管在一定程度上编译可以起到隐藏源码的效果）。`luac` 的全称是 `Lua compiler` 而不是 ~~`Lua Encrypter`~~。

因为 luac 叫编译，所以它的产物叫 **lua 字节码** ，而不是 ~~密文~~，但是 lua 字节码是依赖 cpu 架构的。你执行 luac 的设备是 x86 的 cpu，但你的手机是 arm 的 cpu。这两个不一样，所以电脑编译出来的字节码不能在手机执行。

**lua 和 java 不一样！lua 是跨平台的，但是它的字节码需要相同的 cpu 架构。**

如果你希望达到和 java 一样的效果（编译成 jar 到处都能用），那么请考虑 [Lua JIT](https://github.com/ichenhe/Android-LuaJIT)

**Comment by 123yangu** [comment]
> > 我这边的脚本使用Luac的方式进行加密
> 
> @123yangu 再再说一遍，luac 叫**编译**，不叫~加密~。请不要混用这两个词汇（尽管在一定程度上编译可以起到隐藏源码的效果）。
> 
> 因为 luac 叫编译，所以它的产物叫 **lua 字节码** ，而不是 ~密文~，但是 lua 字节码是依赖 cpu 架构的。你执行 luac 的设备是 x86 的 cpu，但你的手机是 arm 的 cpu。这两个不一样，所以电脑编译出来的字节码不能在手机执行。
> 
> **lua 和 java 不一样！lua 是跨平台的，但是它的字节码需要相同的 cpu 架构。**
> 
> 如果你希望达到和 java 一样的效果（编译成 jar 到处都能用），那么请考虑 [Lua JIT](https://github.com/ichenhe/Android-LuaJIT)

好的，我是搞Android的这个脚本是我们搞lua的工程师写的，他和我说加密了lua脚本，我这个外行来的(os:非常抱歉)，感谢您的回复，谢谢
