### ISSUE TITLE
我发现加了这个库 。混淆代码时候过不去了。一直出错能帮忙给个混淆过滤规则吗跳过lua库就行

### ISSUE THREAD

**Issue by sd3970566** [liangchenhe55/Android-Lua#6]
我发现加了这个库 。混淆代码时候过不去了。一直出错能帮忙给个混淆过滤规则吗跳过lua库就行

**Comment by ichenhe** [comment]
尝试添加 `-keep class org.keplerproject.luajava.**{ *; }`
我会尽快修复此问题。
